[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-server-applescript"
version = "0.1.0"
description = "MCP server for executing AppleScript on macOS"
requires-python = ">=3.10"
dependencies = [
    "mcp",
    "pydantic"
]

[project.scripts]
"applescript_mcp.server" = "applescript_mcp.server:entrypoint"

[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["applescript_mcp"]